trigger:
- master

jobs:
- job: package
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: package/azure-pipelines.yml
- job: sheets
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: sheets/azure-pipelines.yml
